version: "3.8"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
    expose:  #I think we might need this 
      - 5000
      - 80
      
#    environment:
    #  - FLASK_ENV=development
#      - FLASK_APP=/opt/

#    deploy:
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: 5
#        window: 120s
